# Header
menu:
  主页: /
  简历: "http://66666"
  归档: archives
  分类: categories
 #标签云: tags
  关于我: about

# Content
excerpt_link: 阅读详细
fancybox: true

# Miscellaneous
google_analytics:
favicon: /css/images/favicon.png

myduoshuo:
  enable: true  ## duoshuo.com
  short_name: "yourduoshuoname" ## e.g. coney,duoshuo short name.

rss: /atom.xml
